### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by davidlaietta** [bradp/vv#123]
Any vv command that I run is preceded by the following error. Is this something that affects usage?
```
MacBook-Pro:vagrant-local davidlaietta$ vv update
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by bradp** [comment]
Do you have Python installed on your system? There's one bit of python for reading config values out of ~/.vv-config

**Comment by bradp** [comment]
In the next version of vv, this won't be a problem, as the Python dependencies have been removed

**Comment by apsolut** [comment]
When i pull from git (Win8.1) - even when download master zip i get version with python and error on "line 327" , so i just downloaded RAW from your github and there it is replaced with "grep"...  :+1:
