### ISSUE TITLE
vv create is failing

### ISSUE THREAD

**Issue by jazibobs** [bradp/vv#320]
When I create to create a new local site using the `vv create` wizard the process is failing. It gets as far as trying to install WordPress with wp-cli but returns a fatal error:

```
==> default: Updating WordPress Stable...
==> default: PHP Fatal error:  Uncaught Error: Call to undefined function apply_filters() in /srv/www/wordpress-default/wp-includes/load.php:317
==> default: Stack trace:
==> default: #0 /srv/www/wp-cli/php/utils-wp.php(22): wp_debug_mode()
==> default: #1 /srv/www/wp-cli/php/wp-settings-cli.php(59): WP_CLI\Utils\wp_debug_mode()
==> default: #2 /srv/www/wp-cli/php/WP_CLI/Runner.php(806): require('/srv/www/wp-cli...')
==> default: #3 /srv/www/wp-cli/php/WP_CLI/Runner.php(754): WP_CLI\Runner->load_wordpress()
==> default: #4 /srv/www/wp-cli/php/wp-cli.php(21): WP_CLI\Runner->start()
==> default: #5 /srv/www/wp-cli/php/boot-fs.php(17): include('/srv/www/wp-cli...')
==> default: #6 {main}
==> default:   thrown in /srv/www/wordpress-default/wp-includes/load.php on line 317
```

I'm running: 
Ubuntu 16.10
VirtualBox 5.1.6_Ubuntur110634
Vagrant 1.8.6
VVV 1.3.x-working

Do you have any idea why this would be?

**Comment by jazibobs** [comment]
The problem was with wp-cli, I sorted this using the fix descripted at: https://github.com/wp-cli/wp-cli/issues/1310#issuecomment-244624618
