### ISSUE TITLE
prompt for blueprint is duplicated

### ISSUE THREAD

**Issue by norcross** [bradp/vv#337]
when running `vv create`, the prompt is showing twice.
<img width="984" alt="dupe-label" src="https://cloud.githubusercontent.com/assets/98561/22399146/df5fcda2-e564-11e6-8020-255bfd768fa8.png">

**Comment by Raster02** [comment]
The same issue started happening to me as well.

I am getting the following error before the blueprint prompt:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 17 column 7 (char 416)
`
